services:
  spelling-bee-duel:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: spelling-bee-api
    restart: unless-stopped
    ports:
      - "3004:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - /opt/data/spelling-bee-puzzles/data:/app/data:ro
      - ./server/db:/app/db
